# 
FROM python:3.9

# 
WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt

COPY ./.env /code/.env

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./app /code/app

RUN export PYTHONPATH=$PWD
WORKDIR /code
# 
CMD ["uvicorn", "app.server.app:app", "--host", "0.0.0.0", "--port", "7000"]
